import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FloatingWhatsApp from '@/components/ui/FloatingWhatsApp';
import Footer from '@/components/home/footer';
import { ContactFormProvider } from '@/contexts/ContactFormContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ContactFormProvider>
          {children}
          <Footer />
          <FloatingWhatsApp />
        </ContactFormProvider>
      </body>
    </html>
  );
}
