import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import dynamic from 'next/dynamic';
import { ContactFormProvider } from '@/contexts/ContactFormContext';
import { SpeedInsights } from '@vercel/speed-insights/next';

// Lazy load non-critical components
const FloatingWhatsApp = dynamic(() => import('@/components/LazyFloatingWhatsApp'));

const Footer = dynamic(() => import('@/components/home/footer'));

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: 'swap', // Improve font loading performance
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: 'swap', // Improve font loading performance
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link rel="dns-prefetch" href="https://api.whatsapp.com" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ContactFormProvider>
          {children}
          <FloatingWhatsApp />
        </ContactFormProvider>
        <Footer />
        <SpeedInsights />
      </body>
    </html>
  );
}
